### ISSUE TITLE
Is this lib really deprecated?

### ISSUE THREAD

**Issue by rafbgarcia** [absinthe-graphql/absinthe-phoenix-js#8]
If so, what to use instead?

I'm thinking about using it with absinthe `1.4.0-rc.3`.

Thanks

**Comment by bruce** [comment]
The packages in https://github.com/absinthe-graphql/absinthe-socket will be released in the next day or so to go along with the v1.4 stable release. Feel free to play with them and comment before then.

This package was never really as solid as we'd like for production use.
